version: '3.8'

services:
  # Note: Using existing PostgreSQL container (northwind-postgres)
  # Make sure your existing container has Northwind data loaded

  # Backend API (FastAPI)
  backend:
    build: ./backend
    container_name: text-to-sql-backend
    ports:
      - "8070:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@host.docker.internal:5432/northwind
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME}
    networks:
      - text-to-sql-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend (Vue.js)
  frontend:
    build: ./frontend
    container_name: text-to-sql-frontend
    ports:
      - "8080:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - text-to-sql-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  text-to-sql-network:
    driver: bridge
