"""Add preferences column to users table

Revision ID: 4b0241893381
Revises: 6e334094b4d1
Create Date: 2025-06-18 05:03:05.691505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b0241893381'
down_revision: Union[str, None] = '6e334094b4d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_analytics', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('query_analytics', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('query_analytics', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('query_analytics', sa.Column('llm_model', sa.String(length=100), nullable=True))
    op.add_column('query_analytics', sa.Column('llm_cost_estimate', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferences')
    op.drop_column('query_analytics', 'llm_cost_estimate')
    op.drop_column('query_analytics', 'llm_model')
    op.drop_column('query_analytics', 'total_tokens')
    op.drop_column('query_analytics', 'completion_tokens')
    op.drop_column('query_analytics', 'prompt_tokens')
    # ### end Alembic commands ###
