"""Add is_revoked column to refresh_tokens table

Revision ID: 6e334094b4d1
Revises: 722660fb2f27
Create Date: 2025-06-17 09:01:18.969492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e334094b4d1'
down_revision: Union[str, None] = '722660fb2f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('is_revoked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'is_revoked')
    # ### end Alembic commands ###
