"""add database schemas table

Revision ID: 9f3e5a1b7c4d
Revises: 8e2fbd009a9c
Create Date: 2025-01-20 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '9f3e5a1b7c4d'
down_revision = '8e2fbd009a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_schemas',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('connection_id', sa.String(36), nullable=False),
    sa.Column('schema_hash', sa.String(64), nullable=False),
    sa.Column('raw_schema', sa.Text(), nullable=False),
    sa.Column('generated_documentation', sa.Text(), nullable=True),
    sa.Column('table_count', sa.Integer(), nullable=True),
    sa.Column('total_columns', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ondelete='CASCADE'),
    sa.Index('ix_database_schemas_connection_id', 'connection_id'),
    sa.Index('ix_database_schemas_schema_hash', 'schema_hash'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('database_schemas')
    # ### end Alembic commands ### 